name: 'danger-js'
description: 'running danger in action'
inputs:
  dangerfile:  # id of input
    description: 'dangerfile directory'
    required: false
    default: './dangerfile.js'
runs:
  using: 'docker'
  image: 'docker://python:3.7.11-alpine3.14'
  entrypoint: ‘index.sh’
