name: Check

on:
  workflow_run:
    workflows: ["Main"]
    branches: [test-check-workflow]
    types:
      - completed
      
jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "hello check test"
